#############################################################################
# Generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#  Nov 03, 2020 08:27:12 AM +07  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}



    menu .pop48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 1 
    vTcl:DefineAlias ".pop48" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top45 {base} {
    global vTcl
    if {$base == ""} {
        set base .top45
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {{}} -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 735x456+65+24
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "INFORMATION"
    vTcl:DefineAlias "$top" "INFORMATION" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab46 \
        \
        -font {-family {DejaVu Sans} -size 15 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground black -text ------INFORMATION -background #AA96DA \
        -height 513 -highlightcolor black -width 759 
    vTcl:DefineAlias "$top.lab46" "information" vTcl:WidgetProc "INFORMATION" 1
    set site_3_0 $top.lab46
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab51" "Label1" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab52" "Label3" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab53" "Label2" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab54" "Label5" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab55" "Label4" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab56" "Label6" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab58" "Label7" vTcl:WidgetProc "INFORMATION" 1
    button $site_3_0.but53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 0 \
        -text Button 
    vTcl:DefineAlias "$site_3_0.but53" "Button10" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab59" "Label8" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab60" "Label9" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab61" "Label10" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab62" "Label11" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab63" "Label12" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab64" "Label13" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab65" "Label14" vTcl:WidgetProc "INFORMATION" 1
    button $site_3_0.but60 \
        -activebackground #ffffff -activeforeground black -background #234E70 \
        -command exitInformation \
        -font {-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #FBF8BE -highlightcolor black -pady 0 -text EXIT 
    vTcl:DefineAlias "$site_3_0.but60" "exitInformationButton" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black -text {TOTAL VOLTAGE} 
    vTcl:DefineAlias "$site_3_0.lab45" "Label15" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black -text CURRENT 
    vTcl:DefineAlias "$site_3_0.lab46" "Label16" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black -text {REMAINING CAPACITY} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label17" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black -text {NORNAL CAPACITY} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label18" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black -text CYCLES 
    vTcl:DefineAlias "$site_3_0.lab49" "Label19" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black -text {SOFTWARE VERSION} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label20" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black -text RSOC 
    vTcl:DefineAlias "$site_3_0.lab57" "Label21" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 8 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black -text {FET  CONTROL STATUS} 
    vTcl:DefineAlias "$site_3_0.lab67" "Label23" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 7 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black \
        -text {NUMBER OF TEMPERATURE PROBES} 
    vTcl:DefineAlias "$site_3_0.lab68" "Label24" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 7 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black \
        -text {NUMBER OF BATTERY STRING} 
    vTcl:DefineAlias "$site_3_0.lab66" "Label22" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab69 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 8 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black \
        -text {THE FIRST TEMPERATURE} 
    vTcl:DefineAlias "$site_3_0.lab69" "Label25" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab70 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 8 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black \
        -text {THE SECOND TEMPERATURE} 
    vTcl:DefineAlias "$site_3_0.lab70" "Label26" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 8 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black \
        -text {THE THIRD TEMPERATURE} 
    vTcl:DefineAlias "$site_3_0.lab71" "Label27" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 8 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #DDC6B6 -highlightcolor black \
        -text {THE FOURTH TEMPERATURE} 
    vTcl:DefineAlias "$site_3_0.lab72" "Label28" vTcl:WidgetProc "INFORMATION" 1
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.264 -y 0 -rely 0.058 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.264 -y 0 -rely 0.253 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.264 -y 0 -rely 0.156 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.264 -y 0 -rely 0.448 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.264 -y 0 -rely 0.351 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.264 -y 0 -rely 0.546 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.262 -y 0 -rely 0.641 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 0 -relx 1.013 -y 0 -rely 0.307 -width 235 \
        -relwidth 0 -height 85 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.751 -y 0 -rely 0.058 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.751 -y 0 -rely 0.156 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.751 -y 0 -rely 0.253 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 0 -relx 0.752 -y 0 -rely 0.349 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.75 -y 0 -rely 0.448 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.751 -y 0 -rely 0.546 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 0 -relx 0.75 -y 0 -rely 0.641 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but60 \
        -in $site_3_0 -x 0 -relx 0.817 -y 0 -rely 0.78 -width 107 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.04 -y 0 -rely 0.058 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -relx 0.04 -y 0 -rely 0.156 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.04 -y 0 -rely 0.253 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.04 -y 0 -rely 0.351 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.04 -y 0 -rely 0.448 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.04 -y 0 -rely 0.546 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.038 -y 0 -rely 0.641 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.501 -y 0 -rely 0.058 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.501 -y 0 -rely 0.253 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.501 -y 0 -rely 0.156 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 0 -relx 0.501 -y 0 -rely 0.349 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.501 -y 0 -rely 0.448 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.501 -y 0 -rely 0.546 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 0 -relx 0.499 -y 0 -rely 0.643 -width 0 \
        -relwidth 0.249 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx -0.027 -y 0 -width 0 -relwidth 1.033 -height 0 \
        -relheight 1.125 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top45 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

