#############################################################################
# Generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#  Nov 02, 2020 08:34:08 AM +07  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    a_png "./a.png" \
    eng_png "./eng.png" \
    vie_png "./vie.png" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}



    menu .pop48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 1 
    vTcl:DefineAlias ".pop48" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m48" -background #c0c0c0 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 735x455+0+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "AGV ROBOT SYSTEM"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background #EC449E -height 333 \
        -highlightcolor black -width 1950 
    vTcl:DefineAlias "$top.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -background #E93474 \
        -font {-family {Rockwell Condensed} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -image a_png \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab46" "logoasti" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground #EC449E -activeforeground black -background #Ec449e \
        -font {-family {Liberation Serif} -size 22 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #99f443 -highlightcolor black -text {AGV ROBOT SYSTEM} 
    vTcl:DefineAlias "$site_3_0.lab47" "agvrobotsystem" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.06 -width 0 \
        -relwidth 0.474 -height 0 -relheight 0.873 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.509 -y 0 -rely 0.067 -width 0 \
        -relwidth 0.545 -height 0 -relheight 0.787 -anchor nw \
        -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background #8AAAE5 -height 362 \
        -highlightcolor #d9d9d9 -width 758 
    vTcl:DefineAlias "$top.fra46" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    labelframe $site_3_0.lab49 \
        \
        -font {-family {DejaVu Sans} -size 15 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -text {SELECT OPTION} -background #8AAAE5 \
        -height 185 -highlightcolor black -width 317 
    vTcl:DefineAlias "$site_3_0.lab49" "selectOption" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab49
    button $site_4_0.but50 \
        -activebackground #f9f9f9 -activeforeground black -background #4A171E \
        -command setting \
        -font {-family {DejaVu Sans} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #E2B144 -highlightcolor black -pady 0 -text SETTING 
    vTcl:DefineAlias "$site_4_0.but50" "settingButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but52 \
        -activebackground #f9f9f9 -activeforeground black -background #4A171E \
        -command show \
        -font {-family {DejaVu Sans} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #E2B144 -highlightcolor black -pady 0 -text INFORMATION 
    vTcl:DefineAlias "$site_4_0.but52" "showButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but45 \
        -activebackground #f9f9f9 -activeforeground black -background #4A171E \
        -command peripheral \
        -font {-family {DejaVu Sans} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #E2B144 -highlightcolor black -pady 0 -text PERIPHERAL 
    vTcl:DefineAlias "$site_4_0.but45" "peripheralButton" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but50 \
        -in $site_4_0 -x 0 -relx 0.066 -y 0 -rely 0.348 -width 87 -relwidth 0 \
        -height 64 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but52 \
        -in $site_4_0 -x 0 -relx 0.377 -y 0 -rely 0.348 -width 87 -relwidth 0 \
        -height 64 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but45 \
        -in $site_4_0 -x 0 -relx 0.687 -y 0 -rely 0.348 -width 87 -relwidth 0 \
        -height 64 -relheight 0 -anchor nw -bordermode ignore 
    button $site_3_0.but50 \
        -activebackground #f9f9f9 -activeforeground black -background #D2302C \
        -command quit \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #f7f7f9 -highlightcolor black -pady 0 -text EXIT 
    vTcl:DefineAlias "$site_3_0.but50" "exitButton" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ddc6b6 -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab45" "timeLabel" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ddc6b6 -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab47" "pinLabel" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #262223 \
        -font {-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ddc6b6 -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab48" "speedLabel" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command engSetting \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image eng_png -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but44" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command vietSetting \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image vie_png -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but46" "Button2" vTcl:WidgetProc "Toplevel1" 1
    labelframe $site_3_0.lab46 \
        \
        -font {-family {DejaVu Sans} -size 15 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -text CONTROL -background #8AAAE5 -height 185 \
        -width 290 
    vTcl:DefineAlias "$site_3_0.lab46" "selectControl" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab46
    button $site_4_0.but47 \
        -background #4A171E -command startProgram \
        -font {-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #E2B144 -highlightcolor black -text START 
    vTcl:DefineAlias "$site_4_0.but47" "startButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but48 \
        -background #4A171E -command stopProgram \
        -font {-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #E2B144 -highlightcolor black -text STOP 
    vTcl:DefineAlias "$site_4_0.but48" "stopButton" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but47 \
        -in $site_4_0 -x 0 -relx 0.138 -y 0 -rely 0.286 -width 91 -relwidth 0 \
        -height 71 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but48 \
        -in $site_4_0 -x 0 -relx 0.586 -y 0 -rely 0.281 -width 91 -relwidth 0 \
        -height 71 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.013 -y 0 -rely 0.155 -width 0 \
        -relwidth 0.42 -height 0 -relheight 0.478 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.834 -y 0 -rely 0.651 -width 87 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.041 -y 0 -width 0 -relwidth 0.206 \
        -height 0 -relheight 0.104 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.278 -y 0 -width 0 -relwidth 0.154 \
        -height 0 -relheight 0.105 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.488 -y 0 -width 0 -relwidth 0.159 \
        -height 0 -relheight 0.101 -anchor nw -bordermode ignore 
    place $site_3_0.but44 \
        -in $site_3_0 -x 0 -relx 0.874 -y 0 -width 75 -relwidth 0 -height 55 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 0 -relx 0.775 -y 0 -width 75 -relwidth 0 -height 55 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -relx 0.517 -y 0 -rely 0.16 -width 0 \
        -relwidth 0.384 -height 0 -relheight 0.478 -anchor nw \
        -bordermode ignore 
    menu $top.m48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 0 -relx -0.016 -y 0 -rely -0.01 -width 0 -relwidth 1.016 \
        -height 0 -relheight 0.328 -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -y 0 -rely 0.316 -width 0 -relwidth 1.027 -height 0 \
        -relheight 0.851 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

