#############################################################################
# Generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#  Nov 03, 2020 09:06:53 AM +07  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}



    menu .pop48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 1 
    vTcl:DefineAlias ".pop48" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background #FBEAEB -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 735x455+80+21
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 785 450
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "PERIPHERAL"
    vTcl:DefineAlias "$top" "PERIPHERAL" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    labelframe $top.lab47 \
        \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -text {LINE STATUS} -background #4a171e \
        -height 163 -highlightcolor black -width 401 
    vTcl:DefineAlias "$top.lab47" "linestatusLabelframe" vTcl:WidgetProc "PERIPHERAL" 1
    set site_3_0 $top.lab47
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab51" "led1Front" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab52" "led2Front" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab53" "led3Front" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab54" "led4Front" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab55" "led5Front" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab56" "led6Front" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab57" "led7Front" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab58" "led8Front" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #FFC13C \
        -font TkDefaultFont -foreground #673119 -highlightcolor black \
        -text FRONT 
    vTcl:DefineAlias "$site_3_0.lab45" "Label2" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -background #FFC13C \
        -font TkDefaultFont -foreground #673119 -highlightcolor black \
        -text BACK 
    vTcl:DefineAlias "$site_3_0.lab46" "Label10" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab47" "led1Back" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab48" "led3Back" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab49" "led6Back" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab50" "led7Back" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab59" "led2Back" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab60" "Label16" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab61" "led4Back" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab62" "led5Back" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab67" "led8Back" vTcl:WidgetProc "PERIPHERAL" 1
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.202 -y 0 -rely 0.245 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.289 -y 0 -rely 0.245 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.38 -y 0 -rely 0.245 -width 0 \
        -relwidth 0.073 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.468 -y 0 -rely 0.245 -width 0 \
        -relwidth 0.073 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.554 -y 0 -rely 0.243 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.151 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.643 -y 0 -rely 0.245 -width 0 \
        -relwidth 0.073 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.731 -y 0 -rely 0.245 -width 0 \
        -relwidth 0.073 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.818 -y 0 -rely 0.245 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.025 -y 0 -rely 0.184 -width 0 \
        -relwidth 0.15 -height 0 -relheight 0.307 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -relx 0.025 -y 0 -rely 0.613 -width 0 \
        -relwidth 0.15 -height 0 -relheight 0.307 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.2 -y 0 -rely 0.712 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.374 -y 0 -rely 0.711 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.151 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.643 -y 0 -rely 0.712 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.736 -y 0 -rely 0.712 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.287 -y 0 -rely 0.712 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 1.82 -y 0 -rely 0.245 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.459 -y 0 -rely 0.712 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 0 -relx 0.549 -y 0 -rely 0.712 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.823 -y 0 -rely 0.712 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.lab47
    labelframe $top.lab48 \
        \
        -font {-family {DejaVu Sans} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -text {HALL INPUT} -background #4a171e \
        -height 163 -highlightcolor black -width 220 
    vTcl:DefineAlias "$top.lab48" "hallinputLabelframe" vTcl:WidgetProc "PERIPHERAL" 1
    set site_3_0 $top.lab48
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text RIGHT 
    vTcl:DefineAlias "$site_3_0.lab63" "Label19" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab64" "ledRight" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 -activeforeground black -background #FFC13C \
        -font TkDefaultFont -foreground #673119 -highlightcolor black \
        -text LEFT 
    vTcl:DefineAlias "$site_3_0.lab65" "Label21" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab66" "ledLeft" vTcl:WidgetProc "PERIPHERAL" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #FFC13C \
        -font TkDefaultFont -foreground #673119 -highlightcolor black \
        -text RIGHT 
    vTcl:DefineAlias "$site_3_0.lab68" "Label24" vTcl:WidgetProc "PERIPHERAL" 1
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx -0.636 -y 0 -rely 0.613 -width 0 \
        -relwidth 0.273 -height 0 -relheight 0.307 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.455 -y 0 -rely 0.307 -width 0 \
        -relwidth 0.132 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 0 -relx 0.091 -y 0 -rely 0.613 -width 0 \
        -relwidth 0.273 -height 0 -relheight 0.307 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.455 -y 0 -rely 0.675 -width 0 \
        -relwidth 0.132 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.091 -y 0 -rely 0.245 -width 0 \
        -relwidth 0.273 -height 0 -relheight 0.307 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.lab48
    button $top.but46 \
        -activebackground #f9f9f9 -activeforeground black -background #D2302C \
        -command quit -font TkDefaultFont -foreground #f7f7f9 \
        -highlightcolor black -text EXIT 
    vTcl:DefineAlias "$top.but46" "exitButton" vTcl:WidgetProc "PERIPHERAL" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab47 \
        -in $top -x 0 -relx 0.068 -y 0 -rely 0.087 -width 0 -relwidth 0.546 \
        -height 0 -relheight 0.363 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.667 -y 0 -rely 0.089 -width 0 -relwidth 0.299 \
        -height 0 -relheight 0.363 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 0 -relx 0.857 -y 0 -rely 0.857 -width 71 -relwidth 0 \
        -height 51 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

