#############################################################################
# Generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#  Nov 03, 2020 02:24:12 PM +07  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top46 {base} {
    global vTcl
    if {$base == ""} {
        set base .top46
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m47" -background #dbb98f -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 380x231+241+14
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 785 450
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "RESET"
    vTcl:DefineAlias "$top" "reset" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #dbb98f \
        -font TkDefaultFont -foreground #96351b -highlightcolor black \
        -text {New UserName} 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "reset" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #dbb98f \
        -font TkDefaultFont -foreground #96351b -highlightcolor black \
        -text {New PassWord} 
    vTcl:DefineAlias "$top.lab49" "Label2" vTcl:WidgetProc "reset" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #dbb98f \
        -font TkDefaultFont -foreground #96351b -highlightcolor black \
        -text {Confirm password} 
    vTcl:DefineAlias "$top.lab50" "Label3" vTcl:WidgetProc "reset" 1
    entry $top.ent51 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 96 
    vTcl:DefineAlias "$top.ent51" "newUsernameEntry" vTcl:WidgetProc "reset" 1
    entry $top.ent52 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -show * -width 96 
    vTcl:DefineAlias "$top.ent52" "newPasswordEntry" vTcl:WidgetProc "reset" 1
    entry $top.ent53 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -show * -width 96 
    vTcl:DefineAlias "$top.ent53" "confirmPasswordEntry" vTcl:WidgetProc "reset" 1
    button $top.but54 \
        -activebackground #f9f9f9 -activeforeground black -background #317773 \
        -command save -font TkDefaultFont -foreground #e2d1f9 \
        -highlightcolor black -text SAVE 
    vTcl:DefineAlias "$top.but54" "saveButton" vTcl:WidgetProc "reset" 1
    button $top.but55 \
        -activebackground #f9f9f9 -activeforeground black -background #d2302c \
        -command exit -font TkDefaultFont -foreground #f7f7f9 \
        -highlightcolor black -text EXIT 
    vTcl:DefineAlias "$top.but55" "exitButton" vTcl:WidgetProc "reset" 1
    button $top.but56 \
        -activebackground #f9f9f9 -activeforeground black -background #317773 \
        -command cancel -font TkDefaultFont -foreground #e2d1f9 \
        -highlightcolor black -text CANCEL 
    vTcl:DefineAlias "$top.but56" "cancelButton" vTcl:WidgetProc "reset" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab48 \
        -in $top -x 0 -relx 0.129 -y 0 -rely 0.26 -width 0 -relwidth 0.297 \
        -height 0 -relheight 0.052 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.39 -width 0 -relwidth 0.324 \
        -height 0 -relheight 0.095 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.121 -y 0 -rely 0.563 -width 0 -relwidth 0.35 \
        -height 0 -relheight 0.095 -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 0 -relx 0.5 -y 0 -rely 0.242 -width 96 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 0 -relx 0.5 -y 0 -rely 0.385 -width 96 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 0 -relx 0.5 -y 0 -rely 0.55 -width 96 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.368 -y 0 -rely 0.779 -width 71 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.816 -y 0 -width 71 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 0 -relx 0.632 -y 0 -rely 0.779 -width 71 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top46 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

