#############################################################################
# Generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#  Nov 02, 2020 09:53:02 AM +07  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}



    menu .pop48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 1 
    vTcl:DefineAlias ".pop48" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top45 {base} {
    global vTcl
    if {$base == ""} {
        set base .top45
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m49" -background $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 735x246+55+24
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "SETTING"
    vTcl:DefineAlias "$top" "SETTING" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab46 \
        \
        -font {-family {DejaVu Sans} -size 20 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #F8983E -text SETTING -background #072C50 -height 254 \
        -highlightcolor black -width 735 
    vTcl:DefineAlias "$top.lab46" "settingLabelframe" vTcl:WidgetProc "SETTING" 1
    set site_3_0 $top.lab46
    labelframe $site_3_0.lab47 \
        -font TkDefaultFont -foreground #96351E -text {Speed (m/s)} \
        -background #DBB98F -height 247 -highlightcolor black -width 287 
    vTcl:DefineAlias "$site_3_0.lab47" "speedLabelframe" vTcl:WidgetProc "SETTING" 1
    set site_4_0 $site_3_0.lab47
    label $site_4_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #DBB98F \
        -font {-family {DejaVu Sans} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #050505 -highlightcolor black -text LOW 
    vTcl:DefineAlias "$site_4_0.lab45" "Label1" vTcl:WidgetProc "SETTING" 1
    label $site_4_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -background #DBB98F \
        -font {-family {DejaVu Sans} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #050505 -highlightcolor black -text NORMAL 
    vTcl:DefineAlias "$site_4_0.lab46" "Label2" vTcl:WidgetProc "SETTING" 1
    label $site_4_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #DBB98F \
        -font {-family {DejaVu Sans} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #050505 -highlightcolor black -text HIGH 
    vTcl:DefineAlias "$site_4_0.lab47" "Label3" vTcl:WidgetProc "SETTING" 1
    button $site_4_0.but48 \
        -activebackground #f9f9f9 -activeforeground black -background #53354A \
        -command saveSpeedsetting -font TkDefaultFont -foreground #fdf5a6 \
        -highlightcolor black -text SAVE 
    vTcl:DefineAlias "$site_4_0.but48" "Button2" vTcl:WidgetProc "SETTING" 1
    place $site_4_0.lab45 \
        -in $site_4_0 -x 0 -relx 0.105 -y 0 -rely 0.081 -width 0 \
        -relwidth 0.136 -height 0 -relheight 0.134 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab46 \
        -in $site_4_0 -x 0 -relx 0.105 -y 0 -rely 0.243 -width 0 \
        -relwidth 0.24 -height 0 -relheight 0.134 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab47 \
        -in $site_4_0 -x 0 -relx 0.098 -y 0 -rely 0.405 -width 0 \
        -relwidth 0.171 -height 0 -relheight 0.134 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but48 \
        -in $site_4_0 -x 0 -relx 0.174 -y 0 -rely 0.607 -width 75 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    button $site_3_0.but49 \
        -activebackground #f9f9f9 -activeforeground black -background #53354A \
        -command cancelSpeedsetting -font TkDefaultFont -foreground #fdf5a6 \
        -highlightcolor black -text CANCEL 
    vTcl:DefineAlias "$site_3_0.but49" "Button3" vTcl:WidgetProc "SETTING" 1
    entry $site_3_0.ent50 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 86 
    vTcl:DefineAlias "$site_3_0.ent50" "highEntry" vTcl:WidgetProc "SETTING" 1
    entry $site_3_0.ent51 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 86 
    vTcl:DefineAlias "$site_3_0.ent51" "normalEntry" vTcl:WidgetProc "SETTING" 1
    entry $site_3_0.ent52 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 86 
    vTcl:DefineAlias "$site_3_0.ent52" "lowEntry" vTcl:WidgetProc "SETTING" 1
    labelframe $site_3_0.lab53 \
        -font TkDefaultFont -foreground #96351E \
        -text {Battery charge warning level (%)} -background #DBB98F \
        -height 225 -highlightcolor black -width 310 
    vTcl:DefineAlias "$site_3_0.lab53" "Labelframe1" vTcl:WidgetProc "SETTING" 1
    set site_4_0 $site_3_0.lab53
    label $site_4_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #DBB98F \
        -font {-family {DejaVu Sans} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text LEVEL 
    vTcl:DefineAlias "$site_4_0.lab54" "Label4" vTcl:WidgetProc "SETTING" 1
    entry $site_4_0.ent55 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 86 
    vTcl:DefineAlias "$site_4_0.ent55" "batterylevelEntry" vTcl:WidgetProc "SETTING" 1
    button $site_4_0.but57 \
        -activebackground #f9f9f9 -activeforeground black -background #53354A \
        -command saveBatterylevel -font TkDefaultFont -foreground #fdf5a6 \
        -highlightcolor black -text SAVE 
    vTcl:DefineAlias "$site_4_0.but57" "Button4" vTcl:WidgetProc "SETTING" 1
    button $site_4_0.but58 \
        -activebackground #f9f9f9 -activeforeground black -background #53354A \
        -command cancelBatterylevel -font TkDefaultFont -foreground #fdf5a6 \
        -highlightcolor black -text CANCEL 
    vTcl:DefineAlias "$site_4_0.but58" "Button5" vTcl:WidgetProc "SETTING" 1
    place $site_4_0.lab54 \
        -in $site_4_0 -x 0 -relx 0.097 -y 0 -rely 0.404 -width 0 \
        -relwidth 0.21 -height 0 -relheight 0.151 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent55 \
        -in $site_4_0 -x 0 -relx 0.323 -y 0 -rely 0.4 -width 86 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but57 \
        -in $site_4_0 -x 0 -relx 0.323 -y 0 -rely 0.667 -width 71 -relwidth 0 \
        -height 51 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but58 \
        -in $site_4_0 -x 0 -relx 0.71 -y 0 -rely 0.667 -width 71 -relwidth 0 \
        -height 51 -relheight 0 -anchor nw -bordermode ignore 
    button $site_3_0.but56 \
        -activebackground #f9f9f9 -activeforeground black -background #D2302C \
        -command exitSetting -font TkDefaultFont -foreground #F7F7F9 \
        -highlightcolor black -text EXIT 
    vTcl:DefineAlias "$site_3_0.but56" "Button1" vTcl:WidgetProc "SETTING" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.157 -width 0 \
        -relwidth 0.38 -height 0 -relheight 0.969 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.238 -y 0 -rely 0.745 -width 75 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 0 -relx 0.172 -y 0 -rely 0.588 -width 86 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent51 \
        -in $site_3_0 -x 0 -relx 0.172 -y 0 -rely 0.392 -width 86 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent52 \
        -in $site_3_0 -x 0 -relx 0.172 -y 0 -rely 0.235 -width 86 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.45 -y 0 -rely 0.157 -width 0 \
        -relwidth 0.411 -height 0 -relheight 0.882 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 0 -relx 0.887 -y 0 -rely 0.071 -width 71 -relwidth 0 \
        -height 51 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.lab46
    menu $top.m49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1.004 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top45 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

