#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Oct 16, 2020 06:29:48 AM GMT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import gui_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = Login (root)
    gui_support.init(root, top)
    root.mainloop()

w = None
def create_Login(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Login(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Login (w)
    gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Login():
    global w
    w.destroy()
    w = None

class Login:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("634x548+551+121")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("Login")
        top.configure(background="#0080ff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.logoAsti = tk.Label(top)
        self.logoAsti.place(relx=0.505, rely=0.036, height=115, width=308)
        self.logoAsti.configure(activebackground="#f9f9f9")
        self.logoAsti.configure(activeforeground="black")
        self.logoAsti.configure(background="#d9d9d9")
        self.logoAsti.configure(disabledforeground="#a3a3a3")
        self.logoAsti.configure(foreground="#000000")
        self.logoAsti.configure(highlightbackground="#d9d9d9")
        self.logoAsti.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"../gui_arv/a.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.logoAsti.configure(image=_img0)
        self.logoAsti.configure(text='''Label''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.36, rely=0.462, relheight=0.56
                , relwidth=0.639)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''LOGIN''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")

        self.userName = tk.Label(self.Labelframe1)
        self.userName.place(relx=0.121, rely=0.336, height=55, width=65
                , bordermode='ignore')
        self.userName.configure(activebackground="#f9f9f9")
        self.userName.configure(activeforeground="black")
        self.userName.configure(background="#d9d9d9")
        self.userName.configure(disabledforeground="#a3a3a3")
        self.userName.configure(foreground="#000000")
        self.userName.configure(highlightbackground="#d9d9d9")
        self.userName.configure(highlightcolor="black")
        self.userName.configure(text='''USERNAME :''')

        self.passWord = tk.Label(self.Labelframe1)
        self.passWord.place(relx=0.123, rely=0.524, height=37, width=68
                , bordermode='ignore')
        self.passWord.configure(activebackground="#f9f9f9")
        self.passWord.configure(activeforeground="black")
        self.passWord.configure(background="#d9d9d9")
        self.passWord.configure(disabledforeground="#a3a3a3")
        self.passWord.configure(foreground="#000000")
        self.passWord.configure(highlightbackground="#d9d9d9")
        self.passWord.configure(highlightcolor="black")
        self.passWord.configure(text='''PASSWORD :''')

        self.username = tk.Entry(self.Labelframe1)
        self.username.place(relx=0.284, rely=0.404, height=27, relwidth=0.306
                , bordermode='ignore')
        self.username.configure(background="white")
        self.username.configure(disabledforeground="#a3a3a3")
        self.username.configure(font="TkFixedFont")
        self.username.configure(foreground="#000000")
        self.username.configure(highlightbackground="#d9d9d9")
        self.username.configure(highlightcolor="black")
        self.username.configure(insertbackground="black")
        self.username.configure(selectbackground="blue")
        self.username.configure(selectforeground="white")

        self.password = tk.Entry(self.Labelframe1)
        self.password.place(relx=0.284, rely=0.544, height=27, relwidth=0.306
                , bordermode='ignore')
        self.password.configure(background="white")
        self.password.configure(disabledforeground="#a3a3a3")
        self.password.configure(font="TkFixedFont")
        self.password.configure(foreground="#000000")
        self.password.configure(highlightbackground="#d9d9d9")
        self.password.configure(highlightcolor="black")
        self.password.configure(insertbackground="black")
        self.password.configure(selectbackground="blue")
        self.password.configure(selectforeground="white")
        self.password.configure(show="*")

        self.login = tk.Button(self.Labelframe1)
        self.login.place(relx=0.296, rely=0.785, height=44, width=107
                , bordermode='ignore')
        self.login.configure(activebackground="#ececec")
        self.login.configure(activeforeground="#000000")
        self.login.configure(background="#d9d9d9")
        self.login.configure(command=gui_support.login)
        self.login.configure(disabledforeground="#a3a3a3")
        self.login.configure(foreground="#000000")
        self.login.configure(highlightbackground="#d9d9d9")
        self.login.configure(highlightcolor="black")
        self.login.configure(pady="0")
        self.login.configure(text='''LOGIN''')

        self.exitLogin = tk.Button(self.Labelframe1)
        self.exitLogin.place(relx=0.741, rely=0.775, height=44, width=107
                , bordermode='ignore')
        self.exitLogin.configure(activebackground="#ececec")
        self.exitLogin.configure(activeforeground="#000000")
        self.exitLogin.configure(background="#d9d9d9")
        self.exitLogin.configure(command=gui_support.exitLogin)
        self.exitLogin.configure(disabledforeground="#a3a3a3")
        self.exitLogin.configure(foreground="#000000")
        self.exitLogin.configure(highlightbackground="#d9d9d9")
        self.exitLogin.configure(highlightcolor="black")
        self.exitLogin.configure(pady="0")
        self.exitLogin.configure(text='''EXIT''')

if __name__ == '__main__':
    vp_start_gui()





