#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Oct 13, 2020 01:41:28 AM GMT  platform: Windows NT
#    Oct 13, 2020 04:00:51 AM GMT  platform: Windows NT
import Information
import sys
from tkinter import messagebox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def login():
    #print('gui_support.login')
    w.login.configure(background="green")
    w.exitLogin.configure(background="#d9d9d9")
    if (w.username.get()=='ASTI') and (w.password.get()=='asti'):
        print('True')
        Information.create_Information(root)
        w.login.configure(background="#d9d9d9")
        w.username.delete(0,'end')
        w.password.delete(0,'end')
    else:
        messagebox.showinfo("Notification","Username or password is incorrect, please re-enter")
        w.username.delete(0,'end')
        w.password.delete(0,'end')
        w.login.configure(background="#d9d9d9")
    sys.stdout.flush()

def exitLogin():
    #print('gui_support.exitLogin')
    w.exitLogin.configure(background="green")
    w.login.configure(background="#d9d9d9")
    MsgBox=tk.messagebox.askquestion ('Exit Application','Are you sure you want to exit the application',icon = 'warning')
    if MsgBox == 'yes':
       exit()
    else:
        tk.messagebox.showinfo('Return','You will now return to the application screen')
    
    sys.stdout.flush()
    w.exitLogin.configure(background="#d9d9d9")
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import gui
    gui.vp_start_gui()





