#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#    Nov 03, 2020 08:27:12 AM +07  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import information_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = INFORMATION (root)
    information_support.init(root, top)
    root.mainloop()

w = None
def create_INFORMATION(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_INFORMATION(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = INFORMATION (w)
    information_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_INFORMATION():
    global w
    w.destroy()
    w = None

class INFORMATION:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("735x456+65+24")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("INFORMATION")
        top.configure(highlightcolor="black")

        self.information = tk.LabelFrame(top)
        self.information.place(relx=-0.027, rely=0.0, relheight=1.125
                , relwidth=1.033)
        self.information.configure(relief='groove')
        self.information.configure(font="-family {DejaVu Sans} -size 15")
        self.information.configure(text='''------INFORMATION''')
        self.information.configure(background="#AA96DA")

        self.Label1 = tk.Label(self.information)
        self.Label1.place(relx=0.264, rely=0.058, height=40, width=170
                , bordermode='ignore')
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#ffffff")

        self.Label3 = tk.Label(self.information)
        self.Label3.place(relx=0.264, rely=0.253, height=40, width=170
                , bordermode='ignore')
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(background="#ffffff")

        self.Label2 = tk.Label(self.information)
        self.Label2.place(relx=0.264, rely=0.156, height=40, width=170
                , bordermode='ignore')
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(background="#ffffff")

        self.Label5 = tk.Label(self.information)
        self.Label5.place(relx=0.264, rely=0.448, height=40, width=170
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(background="#ffffff")

        self.Label4 = tk.Label(self.information)
        self.Label4.place(relx=0.264, rely=0.351, height=40, width=170
                , bordermode='ignore')
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(background="#ffffff")

        self.Label6 = tk.Label(self.information)
        self.Label6.place(relx=0.264, rely=0.546, height=40, width=170
                , bordermode='ignore')
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(background="#ffffff")

        self.Label7 = tk.Label(self.information)
        self.Label7.place(relx=0.262, rely=0.641, height=40, width=170
                , bordermode='ignore')
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(background="#ffffff")

        self.Button10 = tk.Button(self.information)
        self.Button10.place(relx=1.013, rely=0.306, height=85, width=235
                , bordermode='ignore')
        self.Button10.configure(activebackground="#f9f9f9")
        self.Button10.configure(pady="0")
        self.Button10.configure(text='''Button''')

        self.Label8 = tk.Label(self.information)
        self.Label8.place(relx=0.751, rely=0.058, height=40, width=170
                , bordermode='ignore')
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(background="#ffffff")

        self.Label9 = tk.Label(self.information)
        self.Label9.place(relx=0.751, rely=0.156, height=40, width=170
                , bordermode='ignore')
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(background="#ffffff")

        self.Label10 = tk.Label(self.information)
        self.Label10.place(relx=0.751, rely=0.253, height=40, width=170
                , bordermode='ignore')
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(background="#ffffff")

        self.Label11 = tk.Label(self.information)
        self.Label11.place(relx=0.752, rely=0.349, height=40, width=170
                , bordermode='ignore')
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(background="#ffffff")

        self.Label12 = tk.Label(self.information)
        self.Label12.place(relx=0.75, rely=0.448, height=40, width=170
                , bordermode='ignore')
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(background="#ffffff")

        self.Label13 = tk.Label(self.information)
        self.Label13.place(relx=0.751, rely=0.546, height=40, width=170
                , bordermode='ignore')
        self.Label13.configure(activebackground="#f9f9f9")
        self.Label13.configure(background="#ffffff")

        self.Label14 = tk.Label(self.information)
        self.Label14.place(relx=0.75, rely=0.641, height=40, width=170
                , bordermode='ignore')
        self.Label14.configure(activebackground="#f9f9f9")
        self.Label14.configure(background="#ffffff")

        self.exitInformationButton = tk.Button(self.information)
        self.exitInformationButton.place(relx=0.817, rely=0.78, height=54
                , width=107, bordermode='ignore')
        self.exitInformationButton.configure(activebackground="#ffffff")
        self.exitInformationButton.configure(background="#234E70")
        self.exitInformationButton.configure(command=information_support.exitInformation)
        self.exitInformationButton.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.exitInformationButton.configure(foreground="#FBF8BE")
        self.exitInformationButton.configure(pady="0")
        self.exitInformationButton.configure(text='''EXIT''')

        self.Label15 = tk.Label(self.information)
        self.Label15.place(relx=0.04, rely=0.058, height=40, width=170
                , bordermode='ignore')
        self.Label15.configure(activebackground="#f9f9f9")
        self.Label15.configure(background="#262223")
        self.Label15.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.Label15.configure(foreground="#DDC6B6")
        self.Label15.configure(text='''TOTAL VOLTAGE''')

        self.Label16 = tk.Label(self.information)
        self.Label16.place(relx=0.04, rely=0.156, height=40, width=170
                , bordermode='ignore')
        self.Label16.configure(activebackground="#f9f9f9")
        self.Label16.configure(background="#262223")
        self.Label16.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.Label16.configure(foreground="#DDC6B6")
        self.Label16.configure(text='''CURRENT''')

        self.Label17 = tk.Label(self.information)
        self.Label17.place(relx=0.04, rely=0.253, height=40, width=170
                , bordermode='ignore')
        self.Label17.configure(activebackground="#f9f9f9")
        self.Label17.configure(background="#262223")
        self.Label17.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.Label17.configure(foreground="#DDC6B6")
        self.Label17.configure(text='''REMAINING CAPACITY''')

        self.Label18 = tk.Label(self.information)
        self.Label18.place(relx=0.04, rely=0.351, height=40, width=170
                , bordermode='ignore')
        self.Label18.configure(activebackground="#f9f9f9")
        self.Label18.configure(background="#262223")
        self.Label18.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.Label18.configure(foreground="#DDC6B6")
        self.Label18.configure(text='''NORNAL CAPACITY''')

        self.Label19 = tk.Label(self.information)
        self.Label19.place(relx=0.04, rely=0.448, height=40, width=170
                , bordermode='ignore')
        self.Label19.configure(activebackground="#f9f9f9")
        self.Label19.configure(background="#262223")
        self.Label19.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.Label19.configure(foreground="#DDC6B6")
        self.Label19.configure(text='''CYCLES''')

        self.Label20 = tk.Label(self.information)
        self.Label20.place(relx=0.04, rely=0.546, height=40, width=170
                , bordermode='ignore')
        self.Label20.configure(activebackground="#f9f9f9")
        self.Label20.configure(background="#262223")
        self.Label20.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.Label20.configure(foreground="#DDC6B6")
        self.Label20.configure(text='''SOFTWARE VERSION''')

        self.Label21 = tk.Label(self.information)
        self.Label21.place(relx=0.038, rely=0.641, height=40, width=170
                , bordermode='ignore')
        self.Label21.configure(activebackground="#f9f9f9")
        self.Label21.configure(background="#262223")
        self.Label21.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.Label21.configure(foreground="#DDC6B6")
        self.Label21.configure(text='''RSOC''')

        self.Label23 = tk.Label(self.information)
        self.Label23.place(relx=0.501, rely=0.058, height=40, width=190
                , bordermode='ignore')
        self.Label23.configure(activebackground="#f9f9f9")
        self.Label23.configure(background="#262223")
        self.Label23.configure(font="-family {DejaVu Sans} -size 8 -weight bold")
        self.Label23.configure(foreground="#DDC6B6")
        self.Label23.configure(text='''FET  CONTROL STATUS''')

        self.Label24 = tk.Label(self.information)
        self.Label24.place(relx=0.501, rely=0.253, height=40, width=190
                , bordermode='ignore')
        self.Label24.configure(activebackground="#f9f9f9")
        self.Label24.configure(background="#262223")
        self.Label24.configure(font="-family {DejaVu Sans} -size 7 -weight bold")
        self.Label24.configure(foreground="#DDC6B6")
        self.Label24.configure(text='''NUMBER OF TEMPERATURE PROBES''')

        self.Label22 = tk.Label(self.information)
        self.Label22.place(relx=0.501, rely=0.156, height=40, width=190
                , bordermode='ignore')
        self.Label22.configure(activebackground="#f9f9f9")
        self.Label22.configure(background="#262223")
        self.Label22.configure(font="-family {DejaVu Sans} -size 7 -weight bold")
        self.Label22.configure(foreground="#DDC6B6")
        self.Label22.configure(text='''NUMBER OF BATTERY STRING''')

        self.Label25 = tk.Label(self.information)
        self.Label25.place(relx=0.501, rely=0.349, height=40, width=190
                , bordermode='ignore')
        self.Label25.configure(activebackground="#f9f9f9")
        self.Label25.configure(background="#262223")
        self.Label25.configure(font="-family {DejaVu Sans} -size 8 -weight bold")
        self.Label25.configure(foreground="#DDC6B6")
        self.Label25.configure(text='''THE FIRST TEMPERATURE''')

        self.Label26 = tk.Label(self.information)
        self.Label26.place(relx=0.501, rely=0.448, height=40, width=190
                , bordermode='ignore')
        self.Label26.configure(activebackground="#f9f9f9")
        self.Label26.configure(background="#262223")
        self.Label26.configure(font="-family {DejaVu Sans} -size 8 -weight bold")
        self.Label26.configure(foreground="#DDC6B6")
        self.Label26.configure(text='''THE SECOND TEMPERATURE''')

        self.Label27 = tk.Label(self.information)
        self.Label27.place(relx=0.501, rely=0.546, height=40, width=190
                , bordermode='ignore')
        self.Label27.configure(activebackground="#f9f9f9")
        self.Label27.configure(background="#262223")
        self.Label27.configure(font="-family {DejaVu Sans} -size 8 -weight bold")
        self.Label27.configure(foreground="#DDC6B6")
        self.Label27.configure(text='''THE THIRD TEMPERATURE''')

        self.Label28 = tk.Label(self.information)
        self.Label28.place(relx=0.499, rely=0.643, height=40, width=189
                , bordermode='ignore')
        self.Label28.configure(activebackground="#f9f9f9")
        self.Label28.configure(background="#262223")
        self.Label28.configure(font="-family {DejaVu Sans} -size 8 -weight bold")
        self.Label28.configure(foreground="#DDC6B6")
        self.Label28.configure(text='''THE FOURTH TEMPERATURE''')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





