#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Oct 21, 2020 05:25:24 AM GMT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import information_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = INFORMATION (root)
    information_support.init(root, top)
    root.mainloop()

w = None
def create_INFORMATION(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_INFORMATION(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = INFORMATION (w)
    information_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_INFORMATION():
    global w
    w.destroy()
    w = None

class INFORMATION:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1920x1017+2+0")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("INFORMATION")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.information = tk.LabelFrame(top)
        self.information.place(relx=0.005, rely=0.01, relheight=1.06
                , relwidth=0.99)
        self.information.configure(relief='groove')
        self.information.configure(font="-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0")
        self.information.configure(foreground="black")
        self.information.configure(text='''INFORMATION''')
        self.information.configure(background="#7A88C0")
        self.information.configure(highlightbackground="#d9d9d9")
        self.information.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.information)
        self.Label1.place(relx=0.279, rely=0.056, height=90, width=433
                , bordermode='ignore')
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")

        self.Label2 = tk.Label(self.information)
        self.Label2.place(relx=0.279, rely=0.158, height=90, width=433
                , bordermode='ignore')
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")

        self.Label3 = tk.Label(self.information)
        self.Label3.place(relx=0.279, rely=0.26, height=90, width=433
                , bordermode='ignore')
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")

        self.Label4 = tk.Label(self.information)
        self.Label4.place(relx=0.279, rely=0.362, height=90, width=433
                , bordermode='ignore')
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#ffffff")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")

        self.Label5 = tk.Label(self.information)
        self.Label5.place(relx=0.279, rely=0.464, height=90, width=433
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")

        self.Label6 = tk.Label(self.information)
        self.Label6.place(relx=0.279, rely=0.575, height=89, width=433
                , bordermode='ignore')
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#ffffff")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")

        self.Label7 = tk.Label(self.information)
        self.Label7.place(relx=0.279, rely=0.686, height=89, width=433
                , bordermode='ignore')
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#ffffff")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")

        self.Button10 = tk.Button(self.information)
        self.Button10.place(relx=1.013, rely=0.307, height=85, width=235
                , bordermode='ignore')
        self.Button10.configure(activebackground="#ececec")
        self.Button10.configure(activeforeground="#000000")
        self.Button10.configure(background="#d9d9d9")
        self.Button10.configure(disabledforeground="#a3a3a3")
        self.Button10.configure(foreground="#000000")
        self.Button10.configure(highlightbackground="#d9d9d9")
        self.Button10.configure(highlightcolor="black")
        self.Button10.configure(pady="0")
        self.Button10.configure(text='''Button''')

        self.Label8 = tk.Label(self.information)
        self.Label8.place(relx=0.768, rely=0.056, height=90, width=433
                , bordermode='ignore')
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#ffffff")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")

        self.Label9 = tk.Label(self.information)
        self.Label9.place(relx=0.768, rely=0.158, height=90, width=433
                , bordermode='ignore')
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#ffffff")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")

        self.Label10 = tk.Label(self.information)
        self.Label10.place(relx=0.768, rely=0.26, height=90, width=433
                , bordermode='ignore')
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background="#ffffff")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")

        self.Label11 = tk.Label(self.information)
        self.Label11.place(relx=0.768, rely=0.362, height=90, width=433
                , bordermode='ignore')
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(activeforeground="black")
        self.Label11.configure(background="#ffffff")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(highlightbackground="#d9d9d9")
        self.Label11.configure(highlightcolor="black")

        self.Label12 = tk.Label(self.information)
        self.Label12.place(relx=0.768, rely=0.464, height=90, width=433
                , bordermode='ignore')
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(activeforeground="black")
        self.Label12.configure(background="#ffffff")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(highlightbackground="#d9d9d9")
        self.Label12.configure(highlightcolor="black")

        self.Label13 = tk.Label(self.information)
        self.Label13.place(relx=0.768, rely=0.575, height=84, width=433
                , bordermode='ignore')
        self.Label13.configure(activebackground="#f9f9f9")
        self.Label13.configure(activeforeground="black")
        self.Label13.configure(background="#ffffff")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(foreground="#000000")
        self.Label13.configure(highlightbackground="#d9d9d9")
        self.Label13.configure(highlightcolor="black")

        self.Label14 = tk.Label(self.information)
        self.Label14.place(relx=0.768, rely=0.686, height=89, width=433
                , bordermode='ignore')
        self.Label14.configure(activebackground="#f9f9f9")
        self.Label14.configure(activeforeground="black")
        self.Label14.configure(background="#ffffff")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(foreground="#000000")
        self.Label14.configure(highlightbackground="#d9d9d9")
        self.Label14.configure(highlightcolor="black")

        self.exitInformationButton = tk.Button(self.information)
        self.exitInformationButton.place(relx=0.7, rely=0.816, height=104
                , width=237, bordermode='ignore')
        self.exitInformationButton.configure(activebackground="#ececec")
        self.exitInformationButton.configure(activeforeground="#000000")
        self.exitInformationButton.configure(background="#d70428")
        self.exitInformationButton.configure(command=information_support.exitInformation)
        self.exitInformationButton.configure(disabledforeground="#a3a3a3")
        self.exitInformationButton.configure(font="-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.exitInformationButton.configure(foreground="#000000")
        self.exitInformationButton.configure(highlightbackground="#d9d9d9")
        self.exitInformationButton.configure(highlightcolor="black")
        self.exitInformationButton.configure(pady="0")
        self.exitInformationButton.configure(text='''EXIT''')

        self.Label15 = tk.Label(self.information)
        self.Label15.place(relx=0.026, rely=0.056, height=90, width=475
                , bordermode='ignore')
        self.Label15.configure(activebackground="#f9f9f9")
        self.Label15.configure(activeforeground="black")
        self.Label15.configure(background="#808000")
        self.Label15.configure(disabledforeground="#a3a3a3")
        self.Label15.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label15.configure(foreground="#ffffff")
        self.Label15.configure(highlightbackground="#d9d9d9")
        self.Label15.configure(highlightcolor="black")
        self.Label15.configure(text='''TOTAL VOLTAGE''')

        self.Label16 = tk.Label(self.information)
        self.Label16.place(relx=0.026, rely=0.158, height=90, width=475
                , bordermode='ignore')
        self.Label16.configure(activebackground="#f9f9f9")
        self.Label16.configure(activeforeground="black")
        self.Label16.configure(background="#808000")
        self.Label16.configure(disabledforeground="#a3a3a3")
        self.Label16.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label16.configure(foreground="#ffffff")
        self.Label16.configure(highlightbackground="#d9d9d9")
        self.Label16.configure(highlightcolor="black")
        self.Label16.configure(text='''CURRENT''')

        self.Label17 = tk.Label(self.information)
        self.Label17.place(relx=0.026, rely=0.26, height=90, width=475
                , bordermode='ignore')
        self.Label17.configure(activebackground="#f9f9f9")
        self.Label17.configure(activeforeground="black")
        self.Label17.configure(background="#808000")
        self.Label17.configure(disabledforeground="#a3a3a3")
        self.Label17.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label17.configure(foreground="#ffffff")
        self.Label17.configure(highlightbackground="#d9d9d9")
        self.Label17.configure(highlightcolor="black")
        self.Label17.configure(text='''REMAINING CAPACITY''')

        self.Label18 = tk.Label(self.information)
        self.Label18.place(relx=0.026, rely=0.362, height=90, width=475
                , bordermode='ignore')
        self.Label18.configure(activebackground="#f9f9f9")
        self.Label18.configure(activeforeground="black")
        self.Label18.configure(background="#808000")
        self.Label18.configure(disabledforeground="#a3a3a3")
        self.Label18.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label18.configure(foreground="#ffffff")
        self.Label18.configure(highlightbackground="#d9d9d9")
        self.Label18.configure(highlightcolor="black")
        self.Label18.configure(text='''NORNAL CAPACITY''')

        self.Label19 = tk.Label(self.information)
        self.Label19.place(relx=0.026, rely=0.464, height=90, width=475
                , bordermode='ignore')
        self.Label19.configure(activebackground="#f9f9f9")
        self.Label19.configure(activeforeground="black")
        self.Label19.configure(background="#808000")
        self.Label19.configure(disabledforeground="#a3a3a3")
        self.Label19.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label19.configure(foreground="#ffffff")
        self.Label19.configure(highlightbackground="#d9d9d9")
        self.Label19.configure(highlightcolor="black")
        self.Label19.configure(text='''CYCLES''')

        self.Label20 = tk.Label(self.information)
        self.Label20.place(relx=0.026, rely=0.575, height=89, width=475
                , bordermode='ignore')
        self.Label20.configure(activebackground="#f9f9f9")
        self.Label20.configure(activeforeground="black")
        self.Label20.configure(background="#808000")
        self.Label20.configure(disabledforeground="#a3a3a3")
        self.Label20.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label20.configure(foreground="#ffffff")
        self.Label20.configure(highlightbackground="#d9d9d9")
        self.Label20.configure(highlightcolor="black")
        self.Label20.configure(text='''SOFTWARE VERSION''')

        self.Label21 = tk.Label(self.information)
        self.Label21.place(relx=0.026, rely=0.686, height=89, width=475
                , bordermode='ignore')
        self.Label21.configure(activebackground="#f9f9f9")
        self.Label21.configure(activeforeground="black")
        self.Label21.configure(background="#808000")
        self.Label21.configure(disabledforeground="#a3a3a3")
        self.Label21.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label21.configure(foreground="#ffffff")
        self.Label21.configure(highlightbackground="#d9d9d9")
        self.Label21.configure(highlightcolor="black")
        self.Label21.configure(text='''RSOC''')

        self.Label23 = tk.Label(self.information)
        self.Label23.place(relx=0.516, rely=0.056, height=90, width=475
                , bordermode='ignore')
        self.Label23.configure(activebackground="#f9f9f9")
        self.Label23.configure(activeforeground="black")
        self.Label23.configure(background="#808000")
        self.Label23.configure(disabledforeground="#a3a3a3")
        self.Label23.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label23.configure(foreground="#ffffff")
        self.Label23.configure(highlightbackground="#d9d9d9")
        self.Label23.configure(highlightcolor="black")
        self.Label23.configure(text='''FET  CONTROL STATUS''')

        self.Label24 = tk.Label(self.information)
        self.Label24.place(relx=0.516, rely=0.26, height=90, width=475
                , bordermode='ignore')
        self.Label24.configure(activebackground="#f9f9f9")
        self.Label24.configure(activeforeground="black")
        self.Label24.configure(background="#808000")
        self.Label24.configure(disabledforeground="#a3a3a3")
        self.Label24.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label24.configure(foreground="#ffffff")
        self.Label24.configure(highlightbackground="#d9d9d9")
        self.Label24.configure(highlightcolor="black")
        self.Label24.configure(text='''NUMBER OF TEMPERATURE PROBES''')

        self.Label22 = tk.Label(self.information)
        self.Label22.place(relx=0.516, rely=0.158, height=90, width=475
                , bordermode='ignore')
        self.Label22.configure(activebackground="#f9f9f9")
        self.Label22.configure(activeforeground="black")
        self.Label22.configure(background="#808000")
        self.Label22.configure(disabledforeground="#a3a3a3")
        self.Label22.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label22.configure(foreground="#ffffff")
        self.Label22.configure(highlightbackground="#d9d9d9")
        self.Label22.configure(highlightcolor="black")
        self.Label22.configure(text='''NUMBER OF BATTERY STRING''')

        self.Label25 = tk.Label(self.information)
        self.Label25.place(relx=0.516, rely=0.362, height=90, width=475
                , bordermode='ignore')
        self.Label25.configure(activebackground="#f9f9f9")
        self.Label25.configure(activeforeground="black")
        self.Label25.configure(background="#808000")
        self.Label25.configure(disabledforeground="#a3a3a3")
        self.Label25.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label25.configure(foreground="#ffffff")
        self.Label25.configure(highlightbackground="#d9d9d9")
        self.Label25.configure(highlightcolor="black")
        self.Label25.configure(text='''THE FIRST TEMPERATURE''')

        self.Label26 = tk.Label(self.information)
        self.Label26.place(relx=0.516, rely=0.464, height=90, width=475
                , bordermode='ignore')
        self.Label26.configure(activebackground="#f9f9f9")
        self.Label26.configure(activeforeground="black")
        self.Label26.configure(background="#808000")
        self.Label26.configure(disabledforeground="#a3a3a3")
        self.Label26.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label26.configure(foreground="#ffffff")
        self.Label26.configure(highlightbackground="#d9d9d9")
        self.Label26.configure(highlightcolor="black")
        self.Label26.configure(text='''THE SECOND TEMPERATURE''')

        self.Label27 = tk.Label(self.information)
        self.Label27.place(relx=0.516, rely=0.575, height=89, width=475
                , bordermode='ignore')
        self.Label27.configure(activebackground="#f9f9f9")
        self.Label27.configure(activeforeground="black")
        self.Label27.configure(background="#808000")
        self.Label27.configure(disabledforeground="#a3a3a3")
        self.Label27.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label27.configure(foreground="#ffffff")
        self.Label27.configure(highlightbackground="#d9d9d9")
        self.Label27.configure(highlightcolor="black")
        self.Label27.configure(text='''THE THIRD TEMPERATURE''')

        self.Label28 = tk.Label(self.information)
        self.Label28.place(relx=0.516, rely=0.686, height=89, width=475
                , bordermode='ignore')
        self.Label28.configure(activebackground="#f9f9f9")
        self.Label28.configure(activeforeground="black")
        self.Label28.configure(background="#808000")
        self.Label28.configure(disabledforeground="#a3a3a3")
        self.Label28.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label28.configure(foreground="#ffffff")
        self.Label28.configure(highlightbackground="#d9d9d9")
        self.Label28.configure(highlightcolor="black")
        self.Label28.configure(text='''THE FOURTH TEMPERATURE''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#ececec")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="#000000")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(foreground="#000000")
        Popupmenu1.post(event.x_root, event.y_root)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#ececec")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="#000000")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(foreground="#000000")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





