#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#    Oct 26, 2020 02:52:13 PM +07  platform: Linux

import sys
from JETSON.API import *
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    showInformation()

def exitInformation():
    print('information_support.exitInformation')
    root.destroy()
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
def showInformation():
    try:
        info=AGV().Read_basic_information_batterry()
        
        information=[info[0],info[1],info[2],info[3],info[4],info[5],info[6],info[7],info[8],info[9],info[10],info[11],info[12],info[13]]
        label=[w.Label1,w.Label2,w.Label3,w.Label4,w.Label5,w.Label6,w.Label7,w.Label8,w.Label9,w.Label10,w.Label11,w.Label12,w.Label13,w.Label14]
        for i in range(0,len(label)):
            label[i].configure(text=information[i])
    except:
        pass   
    
    root.after(1000,showInformation)    
            
if __name__ == '__main__':
    import information
    information.vp_start_gui()





