#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Oct 21, 2020 04:19:24 AM GMT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}



    menu .pop48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 1 
    vTcl:DefineAlias ".pop48" "Popupmenu1" vTcl:WidgetProc "" 1
    menu .pop50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 1 
    vTcl:DefineAlias ".pop50" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top45 {base} {
    global vTcl
    if {$base == ""} {
        set base .top45
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m55" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1920x1017+2+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "INFORMATION"
    vTcl:DefineAlias "$top" "INFORMATION" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab46 \
        \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground black -text INFORMATION -background #7A88C0 -height 1078 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 1900 
    vTcl:DefineAlias "$top.lab46" "information" vTcl:WidgetProc "INFORMATION" 1
    set site_3_0 $top.lab46
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab51" "Label1" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab52" "Label2" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab53" "Label3" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab54" "Label4" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab55" "Label5" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab56" "Label6" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab58" "Label7" vTcl:WidgetProc "INFORMATION" 1
    button $site_3_0.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but53" "Button10" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab59" "Label8" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab60" "Label9" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab61" "Label10" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab62" "Label11" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab63" "Label12" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab64" "Label13" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab65" "Label14" vTcl:WidgetProc "INFORMATION" 1
    button $site_3_0.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d70428 -command exitInformation \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text EXIT 
    vTcl:DefineAlias "$site_3_0.but60" "exitInformationButton" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {TOTAL VOLTAGE} 
    vTcl:DefineAlias "$site_3_0.lab45" "Label15" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text CURRENT 
    vTcl:DefineAlias "$site_3_0.lab46" "Label16" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {REMAINING CAPACITY} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label17" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {NORNAL CAPACITY} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label18" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text CYCLES 
    vTcl:DefineAlias "$site_3_0.lab49" "Label19" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {SOFTWARE VERSION} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label20" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text RSOC 
    vTcl:DefineAlias "$site_3_0.lab57" "Label21" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {FET  CONTROL STATUS} 
    vTcl:DefineAlias "$site_3_0.lab67" "Label23" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {NUMBER OF TEMPERATURE PROBES} 
    vTcl:DefineAlias "$site_3_0.lab68" "Label24" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {NUMBER OF BATTERY STRING} 
    vTcl:DefineAlias "$site_3_0.lab66" "Label22" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab69 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {THE FIRST TEMPERATURE} 
    vTcl:DefineAlias "$site_3_0.lab69" "Label25" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab70 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {THE SECOND TEMPERATURE} 
    vTcl:DefineAlias "$site_3_0.lab70" "Label26" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {THE THIRD TEMPERATURE} 
    vTcl:DefineAlias "$site_3_0.lab71" "Label27" vTcl:WidgetProc "INFORMATION" 1
    label $site_3_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black -background #808000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {THE FOURTH TEMPERATURE} 
    vTcl:DefineAlias "$site_3_0.lab72" "Label28" vTcl:WidgetProc "INFORMATION" 1
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.279 -y 0 -rely 0.056 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.279 -y 0 -rely 0.158 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.279 -y 0 -rely 0.26 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.279 -y 0 -rely 0.362 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.279 -y 0 -rely 0.464 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.279 -y 0 -rely 0.575 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.279 -y 0 -rely 0.686 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 0 -relx 1.013 -y 0 -rely 0.307 -width 235 \
        -relwidth 0 -height 85 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.768 -y 0 -rely 0.056 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.768 -y 0 -rely 0.158 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.768 -y 0 -rely 0.26 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 0 -relx 0.768 -y 0 -rely 0.362 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.768 -y 0 -rely 0.464 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.768 -y 0 -rely 0.575 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.078 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 0 -relx 0.768 -y 0 -rely 0.686 -width 0 \
        -relwidth 0.228 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but60 \
        -in $site_3_0 -x 0 -relx 0.7 -y 0 -rely 0.816 -width 237 -relwidth 0 \
        -height 104 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.056 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.158 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.26 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.362 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.464 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.575 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.686 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.516 -y 0 -rely 0.056 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.516 -y 0 -rely 0.26 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.516 -y 0 -rely 0.158 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 0 -relx 0.516 -y 0 -rely 0.362 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.516 -y 0 -rely 0.464 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.516 -y 0 -rely 0.575 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 0 -relx 0.516 -y 0 -rely 0.686 -width 0 \
        -relwidth 0.25 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    menu $top.m55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.005 -y 0 -rely 0.01 -width 0 -relwidth 0.99 \
        -height 0 -relheight 1.06 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top45 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

