#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Oct 19, 2020 03:34:57 AM GMT  platform: Windows NT
#    Oct 19, 2020 03:57:20 AM GMT  platform: Windows NT

from main import *
from tkinter import messagebox
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    

def login():
    print('login_support.login')
    w.loginButton.configure(background="green")
    w.exitButton.configure(background="#d9d9d9")
    
    if (w.userNameEntry.get()=='ASTI') and (w.passWordEntry.get()=='asti'):
        print('True')
        #to do something
        w.loginButton.configure(background="#d9d9d9")
        w.userNameEntry.delete(0,'end')
        w.passWordEntry.delete(0,'end')
    else:
        messagebox.showinfo("Notification","Username or password is incorrect, please re-enter")
        w.userNameEntry.delete(0,'end')
        w.passWordEntry.delete(0,'end')
        w.loginButton.configure(background="#d9d9d9")
    sys.stdout.flush()

def quitLogin():
    print('login_support.quitLogin')
    sys.stdout.flush()
    root.destroy()
    
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import login
    login.vp_start_gui()





