#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Oct 21, 2020 06:06:40 AM GMT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m50" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1920x997+9+147
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "LOGIN" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab46 \
        \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground black -text LOGIN -background #7A88C0 -height 475 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 770 
    vTcl:DefineAlias "$top.lab46" "login" vTcl:WidgetProc "LOGIN" 1
    set site_3_0 $top.lab46
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground #ffffff \
        -background #004040 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor #ffffff -text USERNAME 
    vTcl:DefineAlias "$site_3_0.lab47" "userNameLabel" vTcl:WidgetProc "LOGIN" 1
    entry $site_3_0.ent48 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {ＭＳ ゴシック} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 714 
    vTcl:DefineAlias "$site_3_0.ent48" "userNameEntry" vTcl:WidgetProc "LOGIN" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #004040 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text PASSWORD 
    vTcl:DefineAlias "$site_3_0.lab45" "passWordLabel" vTcl:WidgetProc "LOGIN" 1
    entry $site_3_0.ent46 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {ＭＳ ゴシック} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -show * -width 714 
    vTcl:DefineAlias "$site_3_0.ent46" "passWordEntry" vTcl:WidgetProc "LOGIN" 1
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #808000 -command login -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text LOGIN 
    vTcl:DefineAlias "$site_3_0.but48" "loginButton" vTcl:WidgetProc "LOGIN" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d70428 -command quitLogin -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text EXIT 
    vTcl:DefineAlias "$site_3_0.but49" "exitButton" vTcl:WidgetProc "LOGIN" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.097 -y 0 -rely 0.126 -width 0 \
        -relwidth 0.278 -height 0 -relheight 0.183 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent48 \
        -in $site_3_0 -x 0 -relx 0.392 -y 0 -rely 0.138 -width 714 \
        -relwidth 0 -height 147 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.097 -y 0 -rely 0.378 -width 0 \
        -relwidth 0.277 -height 0 -relheight 0.161 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 0 -relx 0.392 -y 0 -rely 0.367 -width 714 \
        -relwidth 0 -height 147 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -relx 0.285 -y 0 -rely 0.631 -width 287 \
        -relwidth 0 -height 154 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.532 -y 0 -rely 0.631 -width 287 \
        -relwidth 0 -height 154 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.lab46
    menu $top.m50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.12 -width 0 -relwidth 0.97 \
        -height 0 -relheight 0.875 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

