#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#    Nov 03, 2020 02:01:19 PM +07  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = LOGIN (root)
    login_support.init(root, top)
    root.mainloop()

w = None
def create_LOGIN(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_LOGIN(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = LOGIN (w)
    login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_LOGIN():
    global w
    w.destroy()
    w = None

class LOGIN:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("735x228+55+14")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(highlightcolor="black")

        self.login = tk.LabelFrame(top)
        self.login.place(relx=0.0, rely=0.0, relheight=1.013, relwidth=1.029)
        self.login.configure(relief='groove')
        self.login.configure(font="-family {DejaVu Sans} -size 20")
        self.login.configure(text='''LOGIN''')
        self.login.configure(background="#7A88C0")

        self.userNameLabel = tk.Label(self.login)
        self.userNameLabel.place(relx=0.108, rely=0.186, height=44, width=200
                , bordermode='ignore')
        self.userNameLabel.configure(activebackground="#f9f9f9")
        self.userNameLabel.configure(activeforeground="#ffffff")
        self.userNameLabel.configure(background="#080a5e")
        self.userNameLabel.configure(font="-family {DejaVu Sans} -size 20")
        self.userNameLabel.configure(foreground="#eb2188")
        self.userNameLabel.configure(highlightcolor="#ffffff")
        self.userNameLabel.configure(text='''USERNAME''')

        self.userNameEntry = tk.Entry(self.login)
        self.userNameEntry.place(relx=0.381, rely=0.173, height=47
                , relwidth=0.296, bordermode='ignore')
        self.userNameEntry.configure(background="white")
        self.userNameEntry.configure(font="-family {ＭＳ ゴシック} -size 24")
        self.userNameEntry.configure(selectbackground="blue")
        self.userNameEntry.configure(selectforeground="white")

        self.passWordLabel = tk.Label(self.login)
        self.passWordLabel.place(relx=0.107, rely=0.468, height=46, width=199
                , bordermode='ignore')
        self.passWordLabel.configure(activebackground="#f9f9f9")
        self.passWordLabel.configure(background="#080a5e")
        self.passWordLabel.configure(font="-family {DejaVu Sans} -size 20")
        self.passWordLabel.configure(foreground="#eb2188")
        self.passWordLabel.configure(text='''PASSWORD''')

        self.passWordEntry = tk.Entry(self.login)
        self.passWordEntry.place(relx=0.381, rely=0.459, height=47
                , relwidth=0.296, bordermode='ignore')
        self.passWordEntry.configure(background="white")
        self.passWordEntry.configure(font="-family {ＭＳ ゴシック} -size 24")
        self.passWordEntry.configure(selectbackground="blue")
        self.passWordEntry.configure(selectforeground="white")
        self.passWordEntry.configure(show="*")

        self.loginButton = tk.Button(self.login)
        self.loginButton.place(relx=0.185, rely=0.693, height=50, width=130
                , bordermode='ignore')
        self.loginButton.configure(activebackground="#f9f9f9")
        self.loginButton.configure(background="#4a141e")
        self.loginButton.configure(command=login_support.login)
        self.loginButton.configure(font="-family {DejaVu Sans} -size 24")
        self.loginButton.configure(foreground="#e2b144")
        self.loginButton.configure(pady="0")
        self.loginButton.configure(text='''LOGIN''')

        self.exitButton = tk.Button(self.login)
        self.exitButton.place(relx=0.635, rely=0.693, height=50, width=130
                , bordermode='ignore')
        self.exitButton.configure(activebackground="#f9f9f9")
        self.exitButton.configure(background="#d2302c")
        self.exitButton.configure(command=login_support.quitLogin)
        self.exitButton.configure(font="-family {Segoe UI} -size 24")
        self.exitButton.configure(foreground="#f9f7f7")
        self.exitButton.configure(pady="0")
        self.exitButton.configure(text='''EXIT''')

        self.resetButton = tk.Button(self.login)
        self.resetButton.place(relx=0.423, rely=0.693, height=50, width=130
                , bordermode='ignore')
        self.resetButton.configure(activebackground="#f9f9f9")
        self.resetButton.configure(background="#4a141e")
        self.resetButton.configure(command=login_support.reset)
        self.resetButton.configure(font="-family {DejaVu Sans} -size 24")
        self.resetButton.configure(foreground="#e2b144")
        self.resetButton.configure(text='''RESET''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





