#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Oct 21, 2020 06:06:41 AM GMT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = LOGIN (root)
    login_support.init(root, top)
    root.mainloop()

w = None
def create_LOGIN(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_LOGIN(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = LOGIN (w)
    login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_LOGIN():
    global w
    w.destroy()
    w = None

class LOGIN:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1920x997+9+147")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.login = tk.LabelFrame(top)
        self.login.place(relx=0.016, rely=0.12, relheight=0.875, relwidth=0.97)
        self.login.configure(relief='groove')
        self.login.configure(font="-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0")
        self.login.configure(foreground="black")
        self.login.configure(text='''LOGIN''')
        self.login.configure(background="#7A88C0")
        self.login.configure(highlightbackground="#d9d9d9")
        self.login.configure(highlightcolor="black")

        self.userNameLabel = tk.Label(self.login)
        self.userNameLabel.place(relx=0.097, rely=0.126, height=159, width=517
                , bordermode='ignore')
        self.userNameLabel.configure(activebackground="#f9f9f9")
        self.userNameLabel.configure(activeforeground="#ffffff")
        self.userNameLabel.configure(background="#004040")
        self.userNameLabel.configure(disabledforeground="#a3a3a3")
        self.userNameLabel.configure(font="-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0")
        self.userNameLabel.configure(foreground="#ffffff")
        self.userNameLabel.configure(highlightbackground="#d9d9d9")
        self.userNameLabel.configure(highlightcolor="#ffffff")
        self.userNameLabel.configure(text='''USERNAME''')

        self.userNameEntry = tk.Entry(self.login)
        self.userNameEntry.place(relx=0.392, rely=0.138, height=147
                , relwidth=0.383, bordermode='ignore')
        self.userNameEntry.configure(background="white")
        self.userNameEntry.configure(disabledforeground="#a3a3a3")
        self.userNameEntry.configure(font="-family {ＭＳ ゴシック} -size 24 -weight normal -slant roman -underline 0 -overstrike 0")
        self.userNameEntry.configure(foreground="#000000")
        self.userNameEntry.configure(highlightbackground="#d9d9d9")
        self.userNameEntry.configure(highlightcolor="black")
        self.userNameEntry.configure(insertbackground="black")
        self.userNameEntry.configure(selectbackground="blue")
        self.userNameEntry.configure(selectforeground="white")

        self.passWordLabel = tk.Label(self.login)
        self.passWordLabel.place(relx=0.097, rely=0.378, height=140, width=515
                , bordermode='ignore')
        self.passWordLabel.configure(activebackground="#f9f9f9")
        self.passWordLabel.configure(activeforeground="black")
        self.passWordLabel.configure(background="#004040")
        self.passWordLabel.configure(disabledforeground="#a3a3a3")
        self.passWordLabel.configure(font="-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0")
        self.passWordLabel.configure(foreground="#ffffff")
        self.passWordLabel.configure(highlightbackground="#d9d9d9")
        self.passWordLabel.configure(highlightcolor="black")
        self.passWordLabel.configure(text='''PASSWORD''')

        self.passWordEntry = tk.Entry(self.login)
        self.passWordEntry.place(relx=0.392, rely=0.367, height=147
                , relwidth=0.383, bordermode='ignore')
        self.passWordEntry.configure(background="white")
        self.passWordEntry.configure(disabledforeground="#a3a3a3")
        self.passWordEntry.configure(font="-family {ＭＳ ゴシック} -size 24 -weight normal -slant roman -underline 0 -overstrike 0")
        self.passWordEntry.configure(foreground="#000000")
        self.passWordEntry.configure(highlightbackground="#d9d9d9")
        self.passWordEntry.configure(highlightcolor="black")
        self.passWordEntry.configure(insertbackground="black")
        self.passWordEntry.configure(selectbackground="blue")
        self.passWordEntry.configure(selectforeground="white")
        self.passWordEntry.configure(show="*")

        self.loginButton = tk.Button(self.login)
        self.loginButton.place(relx=0.285, rely=0.631, height=154, width=287
                , bordermode='ignore')
        self.loginButton.configure(activebackground="#ececec")
        self.loginButton.configure(activeforeground="#000000")
        self.loginButton.configure(background="#808000")
        self.loginButton.configure(command=login_support.login)
        self.loginButton.configure(disabledforeground="#a3a3a3")
        self.loginButton.configure(font="-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0")
        self.loginButton.configure(foreground="#ffffff")
        self.loginButton.configure(highlightbackground="#d9d9d9")
        self.loginButton.configure(highlightcolor="black")
        self.loginButton.configure(pady="0")
        self.loginButton.configure(text='''LOGIN''')

        self.exitButton = tk.Button(self.login)
        self.exitButton.place(relx=0.532, rely=0.631, height=154, width=287
                , bordermode='ignore')
        self.exitButton.configure(activebackground="#ececec")
        self.exitButton.configure(activeforeground="#000000")
        self.exitButton.configure(background="#d70428")
        self.exitButton.configure(command=login_support.quitLogin)
        self.exitButton.configure(disabledforeground="#a3a3a3")
        self.exitButton.configure(font="-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0")
        self.exitButton.configure(foreground="#ffffff")
        self.exitButton.configure(highlightbackground="#d9d9d9")
        self.exitButton.configure(highlightcolor="black")
        self.exitButton.configure(pady="0")
        self.exitButton.configure(text='''EXIT''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

if __name__ == '__main__':
    vp_start_gui()





