#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Oct 21, 2020 06:22:49 AM GMT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    a_png "./a.png" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}



    menu .pop48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 1 
    vTcl:DefineAlias ".pop48" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m48" -background #c0c0c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1920x1017+-193+303
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm title $top "AGV ROBOT SYSTEM"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background #E93474 -height 333 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 1950 
    vTcl:DefineAlias "$top.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -background #E93474 \
        -disabledforeground #a3a3a3 \
        -font {-family {Rockwell Condensed} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image a_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab46" "logoasti" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground #E93474 -activeforeground black -background #E93474 \
        -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {AGV ROBOT SYSTEM} 
    vTcl:DefineAlias "$site_3_0.lab47" "agvrobotsystem" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -relx -0.051 -y 0 -rely 0.181 -width 0 \
        -relwidth 0.407 -height 0 -relheight 0.599 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.359 -y 0 -rely 0.09 -width 0 \
        -relwidth 0.624 -height 0 -relheight 0.786 -anchor nw \
        -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background #7A88C0 -height 841 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #d9d9d9 \
        -width 1928 
    vTcl:DefineAlias "$top.fra46" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    labelframe $site_3_0.lab46 \
        \
        -font {-family {Lucida Sans Unicode} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground black -text {SELECT LANGUAGE} -background #7A88C0 \
        -height 455 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor #646464646464 -width 601 
    vTcl:DefineAlias "$site_3_0.lab46" "selectLanguage" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab46
    button $site_4_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #808040 -command vietSetting -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground #c0c0c0 \
        -highlightcolor black -pady 0 -text VIE 
    vTcl:DefineAlias "$site_4_0.but47" "vietButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #808040 -command engSetting -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text ENG 
    vTcl:DefineAlias "$site_4_0.but48" "engButton" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but47 \
        -in $site_4_0 -x 0 -relx 0.111 -y 0 -rely 0.374 -width 207 \
        -relwidth 0 -height 184 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but48 \
        -in $site_4_0 -x 0 -relx 0.566 -y 0 -rely 0.374 -width 207 \
        -relwidth 0 -height 184 -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_3_0.lab49 \
        \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground black -text {SELECT OPTION} -background #7A88C0 \
        -height 465 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 810 
    vTcl:DefineAlias "$site_3_0.lab49" "selectOption" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab49
    button $site_4_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #808040 -command setting -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text SETTING 
    vTcl:DefineAlias "$site_4_0.but50" "settingButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #808040 -command show -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text INFORMATION 
    vTcl:DefineAlias "$site_4_0.but52" "showButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #808040 -command peripheral -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text PERIPHERAL 
    vTcl:DefineAlias "$site_4_0.but45" "peripheralButton" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but50 \
        -in $site_4_0 -x 0 -relx 0.037 -y 0 -rely 0.412 -width 217 \
        -relwidth 0 -height 184 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but52 \
        -in $site_4_0 -x 0 -relx 0.341 -y 0 -rely 0.409 -width 237 \
        -relwidth 0 -height 184 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but45 \
        -in $site_4_0 -x 0 -relx 0.682 -y 0 -rely 0.409 -width 237 \
        -relwidth 0 -height 184 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab49
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #e1031e -command quit -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text EXIT 
    vTcl:DefineAlias "$site_3_0.but50" "exitButton" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #c5cc33 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab45" "timeLabel" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #c5cc33 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab47" "pinLabel" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #c5cc33 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab48" "speedLabel" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -relx 0.041 -y 0 -rely 0.214 -width 0 \
        -relwidth 0.327 -height 0 -relheight 0.541 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.477 -y 0 -rely 0.202 -width 0 \
        -relwidth 0.441 -height 0 -relheight 0.553 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.928 -y 0 -width 147 -relwidth 0 \
        -height 124 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.01 -y 0 -width 0 -relwidth 0.164 -height 0 \
        -relheight 0.156 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.187 -y 0 -width 0 -relwidth 0.152 \
        -height 0 -relheight 0.156 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.358 -y 0 -width 0 -relwidth 0.147 \
        -height 0 -relheight 0.155 -anchor nw -bordermode ignore 
    menu $top.m48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 0 -relx -0.016 -y 0 -rely -0.01 -width 0 -relwidth 1.016 \
        -height 0 -relheight 0.328 -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -relx -0.005 -y 0 -rely 0.315 -width 0 -relwidth 1.004 \
        -height 0 -relheight 0.827 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

