#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#    Nov 03, 2020 02:24:12 PM +07  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import reset_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = reset (root)
    reset_support.init(root, top)
    root.mainloop()

w = None
def create_reset(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_reset(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = reset (w)
    reset_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_reset():
    global w
    w.destroy()
    w = None

class reset:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("380x231+241+14")
        top.minsize(1, 1)
        top.maxsize(785, 450)
        top.resizable(1,  1)
        top.title("RESET")
        top.configure(background="#dbb98f")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.129, rely=0.26, height=12, width=113)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#dbb98f")
        self.Label1.configure(foreground="#96351b")
        self.Label1.configure(text='''New UserName''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.105, rely=0.39, height=22, width=123)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(background="#dbb98f")
        self.Label2.configure(foreground="#96351b")
        self.Label2.configure(text='''New PassWord''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.121, rely=0.563, height=22, width=133)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(background="#dbb98f")
        self.Label3.configure(foreground="#96351b")
        self.Label3.configure(text='''Confirm password''')

        self.newUsernameEntry = tk.Entry(top)
        self.newUsernameEntry.place(relx=0.5, rely=0.242, height=23
                , relwidth=0.253)
        self.newUsernameEntry.configure(background="white")
        self.newUsernameEntry.configure(font="TkFixedFont")
        self.newUsernameEntry.configure(selectbackground="blue")
        self.newUsernameEntry.configure(selectforeground="white")

        self.newPasswordEntry = tk.Entry(top)
        self.newPasswordEntry.place(relx=0.5, rely=0.385, height=23
                , relwidth=0.253)
        self.newPasswordEntry.configure(background="white")
        self.newPasswordEntry.configure(font="TkFixedFont")
        self.newPasswordEntry.configure(selectbackground="blue")
        self.newPasswordEntry.configure(selectforeground="white")
        self.newPasswordEntry.configure(show="*")

        self.confirmPasswordEntry = tk.Entry(top)
        self.confirmPasswordEntry.place(relx=0.5, rely=0.55, height=23
                , relwidth=0.253)
        self.confirmPasswordEntry.configure(background="white")
        self.confirmPasswordEntry.configure(font="TkFixedFont")
        self.confirmPasswordEntry.configure(selectbackground="blue")
        self.confirmPasswordEntry.configure(selectforeground="white")
        self.confirmPasswordEntry.configure(show="*")

        self.saveButton = tk.Button(top)
        self.saveButton.place(relx=0.368, rely=0.779, height=31, width=71)
        self.saveButton.configure(activebackground="#f9f9f9")
        self.saveButton.configure(background="#317773")
        self.saveButton.configure(command=reset_support.save)
        self.saveButton.configure(foreground="#e2d1f9")
        self.saveButton.configure(text='''SAVE''')

        self.exitButton = tk.Button(top)
        self.exitButton.place(relx=0.816, rely=0.0, height=31, width=71)
        self.exitButton.configure(activebackground="#f9f9f9")
        self.exitButton.configure(background="#d2302c")
        self.exitButton.configure(command=reset_support.exit)
        self.exitButton.configure(foreground="#f7f7f9")
        self.exitButton.configure(text='''EXIT''')

        self.cancelButton = tk.Button(top)
        self.cancelButton.place(relx=0.632, rely=0.779, height=31, width=71)
        self.cancelButton.configure(activebackground="#f9f9f9")
        self.cancelButton.configure(background="#317773")
        self.cancelButton.configure(command=reset_support.cancel)
        self.cancelButton.configure(foreground="#e2d1f9")
        self.cancelButton.configure(text='''CANCEL''')

if __name__ == '__main__':
    vp_start_gui()





