#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#    Nov 03, 2020 12:48:23 PM +07  platform: Linux

import sys
import pickle
from tkinter import messagebox
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def cancel():
    print('reset_support.cancel')
    msg=messagebox.askquestion("Cancel","Are you sure you want to cancel",parent=root)
    if msg=="yes":
        w.confirmPasswordEntry.delete(0,'end')
        w.newPasswordEntry.delete(0,'end')
        w.newUsernameEntry.delete(0,'end')
    else:
        pass    
    sys.stdout.flush()

def exit():
    print('reset_support.exit')
    root.destroy()
    sys.stdout.flush()

def save():
    print('reset_support.save')
    if(w.newPasswordEntry.get()==w.confirmPasswordEntry.get()):
        msg=messagebox.askquestion("Save","Are you sure you want to save",parent=root)
        if msg=='yes':
            data={'username':w.newUsernameEntry.get(),'password':w.newPasswordEntry.get()}
            f = open("asti.pickle", "wb")
            f.write(pickle.dumps(data)) 
            f.close()
        else:
            pass 
    else:
        messagebox.showerror("Error","Confirm password inconrect",parent=root)       
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import reset
    reset.vp_start_gui()





