#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Oct 21, 2020 06:06:00 AM GMT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1337x728+1+137
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "SELECTINFORMATION" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab46 \
        \
        -font {-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground black -text {SELECT  INFORMATION} -background #0080c0 \
        -height 697 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 1292 
    vTcl:DefineAlias "$top.lab46" "selectinformationLabelframe" vTcl:WidgetProc "SELECTINFORMATION" 1
    set site_3_0 $top.lab46
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #808000 -command pinInformation \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {PIN INFORMATION} 
    vTcl:DefineAlias "$site_3_0.but47" "pinInformation" vTcl:WidgetProc "SELECTINFORMATION" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #808000 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {SOME THINGS} 
    vTcl:DefineAlias "$site_3_0.but49" "some things" vTcl:WidgetProc "SELECTINFORMATION" 1
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #e1031e -command eixt -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 23 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text EXIT 
    vTcl:DefineAlias "$site_3_0.but50" "exitButton" vTcl:WidgetProc "SELECTINFORMATION" 1
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.139 -y 0 -rely 0.345 -width 307 \
        -relwidth 0 -height 144 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.526 -y 0 -rely 0.33 -width 327 -relwidth 0 \
        -height 154 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.844 -y 0 -rely 0.029 -width 207 \
        -relwidth 0 -height 144 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.041 -width 0 -relwidth 0.966 \
        -height 0 -relheight 0.956 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

