#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Oct 21, 2020 06:06:12 AM GMT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import selectInformation_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = SELECTINFORMATION (root)
    selectInformation_support.init(root, top)
    root.mainloop()

w = None
def create_SELECTINFORMATION(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_SELECTINFORMATION(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = SELECTINFORMATION (w)
    selectInformation_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_SELECTINFORMATION():
    global w
    w.destroy()
    w = None

class SELECTINFORMATION:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1337x728+1+137")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.selectinformationLabelframe = tk.LabelFrame(top)
        self.selectinformationLabelframe.place(relx=0.022, rely=0.041
                , relheight=0.956, relwidth=0.966)
        self.selectinformationLabelframe.configure(relief='groove')
        self.selectinformationLabelframe.configure(font="-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.selectinformationLabelframe.configure(foreground="black")
        self.selectinformationLabelframe.configure(text='''SELECT  INFORMATION''')
        self.selectinformationLabelframe.configure(background="#0080c0")
        self.selectinformationLabelframe.configure(highlightbackground="#d9d9d9")
        self.selectinformationLabelframe.configure(highlightcolor="black")

        self.pinInformation = tk.Button(self.selectinformationLabelframe)
        self.pinInformation.place(relx=0.139, rely=0.345, height=144, width=307
                , bordermode='ignore')
        self.pinInformation.configure(activebackground="#ececec")
        self.pinInformation.configure(activeforeground="#000000")
        self.pinInformation.configure(background="#808000")
        self.pinInformation.configure(command=selectInformation_support.pinInformation)
        self.pinInformation.configure(disabledforeground="#a3a3a3")
        self.pinInformation.configure(font="-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.pinInformation.configure(foreground="#000000")
        self.pinInformation.configure(highlightbackground="#d9d9d9")
        self.pinInformation.configure(highlightcolor="black")
        self.pinInformation.configure(pady="0")
        self.pinInformation.configure(text='''PIN INFORMATION''')

        self.some_things = tk.Button(self.selectinformationLabelframe)
        self.some_things.place(relx=0.526, rely=0.33, height=154, width=327
                , bordermode='ignore')
        self.some_things.configure(activebackground="#ececec")
        self.some_things.configure(activeforeground="#000000")
        self.some_things.configure(background="#808000")
        self.some_things.configure(disabledforeground="#a3a3a3")
        self.some_things.configure(font="-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.some_things.configure(foreground="#000000")
        self.some_things.configure(highlightbackground="#d9d9d9")
        self.some_things.configure(highlightcolor="black")
        self.some_things.configure(pady="0")
        self.some_things.configure(text='''SOME THINGS''')

        self.exitButton = tk.Button(self.selectinformationLabelframe)
        self.exitButton.place(relx=0.844, rely=0.029, height=144, width=207
                , bordermode='ignore')
        self.exitButton.configure(activebackground="#ececec")
        self.exitButton.configure(activeforeground="#000000")
        self.exitButton.configure(background="#e1031e")
        self.exitButton.configure(command=selectInformation_support.eixt)
        self.exitButton.configure(disabledforeground="#a3a3a3")
        self.exitButton.configure(font="-family {Segoe UI} -size 23 -weight bold -slant roman -underline 0 -overstrike 0")
        self.exitButton.configure(foreground="#000000")
        self.exitButton.configure(highlightbackground="#d9d9d9")
        self.exitButton.configure(highlightcolor="black")
        self.exitButton.configure(pady="0")
        self.exitButton.configure(text='''EXIT''')

if __name__ == '__main__':
    vp_start_gui()





